FROM nginx:latest

COPY pushca-widget.html /usr/share/nginx/html

COPY js /usr/share/nginx/html/js

COPY cer /usr/share/nginx/html/cer

COPY cer/pushca-rc.crt /usr/share/nginx/conf

COPY cer/pushca-rc.key /usr/share/nginx/conf

