package bmv.org.pushca.client.model;

public enum Command {
  SEND_MESSAGE,
  SEND_MESSAGE_WITH_ACKNOWLEDGE,
  SEND_MESSAGE_WITH_PRESERVED_ORDER,
  SEND_ENVELOPES,
  PING,
  REFRESH_TOKEN,
  ACKNOWLEDGE;
}
