spring:
  application:
    name: pushca-verifier

management:
  endpoint.health.show-details: always
  endpoints.web.exposure:
      include: '*'
      exclude: 'shutdown'

server:
  undertow:
    threads:
      io: 800
    accesslog:
      enabled: true
      pattern: "%t %a %r %s (%D ms)"
    options:
      server:
        record-request-start-time: true

logging:
  level:
    root: INFO

verification:
  pushca-coordinator:
#    url: http://localhost:8050
#    url: http://ec2-13-60-25-150.eu-north-1.compute.amazonaws.com:8070
#    url: https://app-rc.multiloginapp.net/pushca
     url: http://static.48.197.202.116.clients.your-server.de:8070
#should be always odd
  number-of-clients: 49
  processor-type: MESSAGE_WITH_ACKNOWLEDGE_REST
  preserve-order: false
  load-test-runner:
    number: 50
#   number: 120
  client-connection-pool:
    size: 2
  load-test:
    repeat-interval-ms: 1
  response:
    timeout:
      ms: 15000

