openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8050
  description: Generated server url
paths:
  /send-notification:
    post:
      tags:
      - public-api-controller
      summary: Send notification
      operationId: sendNotification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendNotificationRequest'
        required: true
      responses:
        "200":
          description: Success
        "429":
          description: Too many requests
  /send-notification-with-acknowledge:
    post:
      tags:
      - public-api-controller
      summary: Send notification with acknowledge
      operationId: sendNotificationWithAcknowledge
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendNotificationWithAcknowledgeRequest'
        required: true
      responses:
        "408":
          description: Acknowledge time out
        "200":
          description: Success
  /open-connection:
    post:
      tags:
      - public-api-controller
      summary: Open connection
      operationId: openConnection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenConnectionRequest'
        required: true
      responses:
        "429":
          description: Too many requests
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenConnectionResponse'
components:
  schemas:
    ClientSearchData:
      type: object
      properties:
        workSpaceId:
          type: string
        accountId:
          type: string
        deviceId:
          type: string
        applicationId:
          type: string
        findAny:
          type: boolean
        exclude:
          type: array
          items:
            $ref: '#/components/schemas/PClient'
    PClient:
      type: object
      properties:
        workSpaceId:
          type: string
        accountId:
          type: string
        deviceId:
          type: string
        applicationId:
          type: string
    SendNotificationRequest:
      type: object
      properties:
        id:
          type: string
        filter:
          $ref: '#/components/schemas/ClientSearchData'
        preserveOrder:
          type: boolean
        message:
          type: string
    SendNotificationWithAcknowledgeRequest:
      type: object
      properties:
        id:
          type: string
        client:
          $ref: '#/components/schemas/PClient'
        preserveOrder:
          type: boolean
        message:
          type: string
    OpenConnectionRequest:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/PClient'
        pusherInstanceId:
          type: string
    OpenConnectionResponse:
      type: object
      properties:
        pusherInstanceId:
          type: string
        externalAdvertisedUrl:
          type: string
        internalAdvertisedUrl:
          type: string
